### ISSUE TITLE
could not find hg for clone of Eigen_download

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/SYCL-DNN#2]

**Comment by DuncanMcBain** [comment]
In case anyone else runs into the same issue and finds this, the reason for the error is that Eigen needs the [Mercurial DVCS](https://www.mercurial-scm.org/) to be installed, as Eigen is [hosted on Atlassian's Bitbucket](https://bitbucket.org/codeplaysoftware/eigen-fork/src/default/). The command for Mercurial is `hg` and so CMake complains that this command cannot be found. Installing Mercurial via your preferred means is the solution.

**Comment by jinz2014** [comment]
Thanks for your explanation.
