### ISSUE TITLE
how we can run tests and benchmark

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/SYCL-DNN#3]
// Can then run tests
ctest
// If compiled with benchmark support, can run benchmarks exclusively
ctest -C Benchmark -E test

Can you specify how we can run tests and benchmark ?   Thanks. 

$:~/SYCL-DNN$ ctest
*********************************
No test configuration file found!
*********************************

$ ctest -C Benchmark -E test
No tests were found!!!

**Comment by DuncanMcBain** [comment]
Hi @jinz2014,
The `-E test` flag in the `ctest` call excludes the tests, so omitting this and just running `ctest -C Benchmark` will run both tests and benchmarks.

Also `ctest` expects to run inside the build directory, otherwise it cannot find the tests to run.
