### ISSUE TITLE
build.sh and requirements

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/SYCL-DNN#4]
In the repository, build.sh may be deleted, and the 'hg' requirement is added. 
It is helpful to print the device information when running the test and benchmark. It is not clear to users which device they are running on. 

Thanks for your update.

**Comment by rodburns** [comment]
I'm afraid I am not totally clear on what you are requesting here. Would you like SYCL-DNN to print out the device it is running on before execution?
Can you clarify the point about the build.sh file?
Thank you.

**Comment by jinz2014** [comment]
I assume that users can build the software with either cmake or build.sh, but build.sh is not mentioned in the README.

**Comment by DuncanMcBain** [comment]
Hi @jinz2014, the `build.sh` was only really used for our Travis builds, which have been disabled for now. As the README suggests, it would be best to use pure CMake for building the library and tests.
