### ISSUE TITLE
bias question

### ISSUE THREAD

**Issue by jinz2014** [codeplaysoftware/SYCL-DNN#7]
Can you please provide a sample using bias in a convolution ?  The convolution sample only initialize weights of a filter. Please advise.  Thanks.

**Comment by DuncanMcBain** [comment]
Hi @jinz2014, we don't support biases in our convolution operations, nor do we have a standalone BiasAdd operator. I did some work casually in implementing one but never had it at a satisfactory stage (and am working on other things for now).

It would be interesting to add support for biases somehow (possibly as part of convolutions) but it's not work we have planned for the moment.

**Comment by jinz2014** [comment]
DNN needs the support for biases.
